version: '3.7'

volumes:
  db:

services:
  db:
    image: postgres:9-alpine
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123qweasd
      POSTGRES_DB: deprop
